dataset:
  dataset_name: "ArmisticeAI/OCTDL2024"
  num_classes: 5
  inchans: 3

training:
  batch_size: 32
  loss_fn: "cross-entropy-loss"
  optimizer: "adam"
  learning_rate: 0.0001
  num_epochs: 10

model:
  model_name: "resnet18"

output:
  model_save_dir: "models"
  model_save_name: "resnet18.pth"
  train_output_save_dir: "outputs/resnet18-train"
  test_output_save_dir: "outputs/resnet18-evaluation"

